version: 2.1
jobs:
  build-and-push:
    docker:
      - image: cimg/node:14.19
    environment:
      ecr_url: $ECR_URL
      ecr_password: $ECR_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          verstion: 20.10.14
      - run: yarn
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build docker image
          command: docker build . -t $
      - run: 
          name: Push
          command: "echo $ecr-password | docker login -u AWS --password-stdin
          docker push $ecr-url"

workflows:
  build:
    jobs:
      - build-and-push