version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - setup_remote_docker:
          verstion: 20.10.14
      - run: yarn
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build docker image
          command: docker build . -t test-image

workflows:
  build:
    jobs:
      - build