version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '14.8.1'
      - run: yarn
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build docker image
          command: docker build . -t test-image