version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - run: node --version
      - run: yarn
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build docker image
          command: docker build . -t test-image