# CircleCI configuration file
version: 2.1

jobs:
  build
    steps
      - checkout
      - run:
          name: Tests
          command: yarn test
      - run: 
          name: Build Docker Image
          command: docker build . -t test-image
