version: 2.1
jobs:
  build-and-push:
    docker:
      - image: cimg/node:14.19
      environment:
        ECR_URL: $ECR_URL
        ECR_PASSWORD: $ECR_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          verstion: 20.10.14
      - run: yarn
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build docker image
          command: docker build . -t $ECR_URL
      - run: 
          name: Push
          command: |
          echo $ECR_PASSWORD | docker login -u AWS --password-stdin
          docker push $ECR_URL

workflows:
  build:
    jobs:
      - build-and-push