version: 2.1

branch: master

jobs:
  build-and-push:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - setup_remote_docker:
          verstion: 20.10.14
      - run: yarn
      - run:
          name: Test
          command: yarn test
      - run: sh -c env | grep ECR
      - run:
          name: Build docker image
          command: docker build . -t $ECR_URL
      - run: 
          name: Push
          command: |
            echo $ECR_PASSWORD | docker login -u AWS --password-stdin $ECR_URL
            docker push $ECR_URL

workflows:
  build:
    branches:
      only: master
    jobs:
      - build-and-push