version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - setup_remote_docker:
          verstion: 20.10.14
      - run: 
          name: Install Docker
          command: curl -fsSL https://get.docker.com -o get-docker.sh && DRY_RUN=1 sh ./get-docker.sh
      - run: yarn
      - run: ls
      - run: pwd
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build docker image
          command: docker build . -t test-image